import {defineScorerFunctionContract} from "../../../../__test__/scorer-test-support.js";

defineScorerFunctionContract(import.meta.url, {
  "index.ts": [
    "recommendationItemQuestion",
    "recommendationQuestionTokens",
    "isPageNumberOnly",
    "startsBullet",
    "startsRecommendationBullet",
    "recommendationLineStart",
    "recommendationBoundaryLine",
    "collectRecommendationSegment",
    "recommendationSegments",
    "explicitRecommendationLineStart",
    "collectExplicitRecommendationBlock",
    "explicitRecommendationSegments",
    "atomicRecommendationBoundary",
    "buildAtomicRecommendationSegments",
    "recommendationSubjectCompatible",
    "recommendationQuestionCoverage",
    "recommendationAnswerWindow",
    "recommendationAliasSupport",
    "anticoagulationContraPolarity",
    "recommendationPresenceMismatch",
    "appointmentTargetTokens",
    "targetCoverage",
    "appointmentContextTokens",
    "contextCoverage",
    "recommendationSegmentAnswerHit",
    "genericPopulationAnswerText",
    "populationStem",
    "hasSpecificPopulationAlternative",
    "followUpFrequencyAnswer",
    "explicitRecommendationTargetAdjustment",
    "bestRecommendationItemSupport",
    "broadRecommendationQuestion",
    "recommendationCueSegment",
    "bestRecommendationBlockSupport",
  ],
});
