import {defineScorerFunctionContract} from "../../../../__test__/scorer-test-support.js";

defineScorerFunctionContract(import.meta.url, {
  "index.ts": [
    "canonicalNumber",
    "canonicalIntervalTuples",
    "strictNumbers",
    "canonicalUnitAfter",
    "numericTuples",
    "familySkeleton",
    "unitClass",
    "buildIntervalFamily",
    "buildNumericFamily",
    "negativeOrAmbiguousQuestion",
    "detectRelationRole",
    "questionComparator",
    "focusTokens",
    "conditionSpecs",
    "isBoundaryLine",
    "splitBoundedText",
    "buildRelationTupleFragments",
    "sliceTargetScope",
    "roleCueMatches",
    "scopesForRole",
    "numberPresent",
    "comparatorNearValue",
    "requiredUnitClass",
    "focusCompatible",
    "memberMatchesScope",
    "localConditionDirection",
    "conditionsCompatible",
    "resolveRelationTuple",
    "applySingleRelationTupleResolver",
  ],
});
