import {defineScorerFunctionContract} from "../../../../__test__/scorer-test-support.js";

defineScorerFunctionContract(import.meta.url, {
  "cloze.ts": [
    "clozeQuestionParts",
    "clozeApplicable",
    "clozeFocusTokens",
    "clozeCoreTokens",
    "clozeAnswerPhraseEntries",
    "clozeHasUnitCue",
    "lastTokenDistance",
    "clozeContrastPenalty",
    "relevantClozeQuestionNumbers",
    "clozeLocalHasRelevantQuestionNumber",
    "clozeTailHasConflictingNumber",
    "clozeTailHasTimingCue",
    "bestClozeGapSupport",
  ],
  "condition-family.ts": [
    "conditionFamily",
    "nearestConditionFamily",
  ],
  "condition-focus.ts": ["specificConditionNumberFocusTokens"],
  "condition-pair.ts": [
    "answerValueCondition",
    "conditionPairAdjustment",
  ],
  "count-relation.ts": [
    "countQuestion",
    "countFocusTokens",
    "countNumberSearchPhrases",
    "countRelationAnswerOption",
    "countCueHit",
    "positiveStructuralHit",
    "countTargetNear",
    "bestCountRelationSupport",
  ],
  "exact-option.ts": [
    "numericOptionAnswer",
    "denseNumericSingleQuestion",
    "exactNumericOptionQuestion",
    "numericExactPhrases",
    "hourAliasPhrases",
    "segmentContainsBoundedPhrase",
    "bestExactNumericOptionSupport",
    "bestExactHourAliasOptionSupport",
  ],
  "numeric-condition.ts": [
    "questionMarkerConditions",
    "markerConditionsMatch",
    "conditionedNumberPhrases",
    "exactNumericForms",
    "numericSearchBoundary",
    "findNumericFormHits",
    "sourceConditionHits",
    "nextConditionHit",
    "interveningNumberCount",
    "numericConditionDirectionOk",
    "numericConditionAnchorSatisfied",
    "questionNumericConditionAnchors",
    "numericConditionSources",
    "bestNumericConditionSupport",
    "bestConditionedNumberSupport",
  ],
  "subject-bound.ts": [
    "subjectBoundNumericClauses",
    "numericOptionValues",
    "numericComparatorNearValue",
    "bestSubjectBoundNumericClauseSupport",
  ],
});
